
---

- name: setup jenkins master on ubuntu
  hosts: jenkins_master
  strategy: free # linear, serial, free
  gather_facts: false
  become: true
  vars:
    ROOT: /root
    TOMCAT_ROOT: "{{ROOT}}/.tomcat"

  tasks:
  - name: download jenkins.war
    get_url:
      url: http://nexus.oss.balaji.network:8081/nexus/content/repositories/releases/com/bit/
      dest: "{{TOMCAT_ROOT}}/webapps/ROOT.war"
      
