
---

- name: deploy artifact into tomcat test server
  hosts: tomcat_test
  strategy: free # linear, serial, free
  gather_facts: false
  become: true
  vars:
    ROOT: {{ansible_env.HOME}}/root
    TOMCAT_ROOT: "{{ROOT}}/.tomcat"

  tasks:
  - name: download artifact from nexus oss
    get_url:
      url: http://nexus.oss.balaji.network:8081/nexus/content/repositories/releases/com/bit/
      username: admin
      password: admin123
      dest: "{{TOMCAT_ROOT}}/webapps/ROOT.war
