---

- name: setup docker on ubuntu
  
  hosts: jenkinsmaster
  
  gather_facts: false
  
  become: true

  tasks:

  - name: uninstall old docker versions
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: add docker official gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

  - name: install docker-ce
    apt:
      name:
        - aptitude
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce
      update_cache: yes
