- name: setup jenkins master on ubuntu
  
  hosts: jenkinsmaster
  
  gather_facts: false
  
  become: true
  
  vars:
    ROOT: /root
    TOMCAT_ROOT: "{{ ROOT }}/tomcat"
  
  tasks:
  
    - name: update packages index
      apt:
        update_cache: yes
        
    - name: install wget openjdk-8-jdk
      apt:
        name:
          - wget
          - openjdk-8-jdk
          
    - name: download tomcat
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
        dest: "{{ ROOT }}/apache-tomcat-8.5.41.tar.gz"
        
    - name: extract tomcat tarball
      unarchive:
        remote_src: yes
        src: "{{ ROOT }}/apache-tomcat-8.5.41.tar.gz"
        dest: "{{ ROOT }}"
        
    - name: remove tomcat tarball
      file:
        path: "{{ ROOT }}/apache-tomcat-8.5.41.tar.gz"
        state: absent
        
    - name: rename tomcat directory
      command: creates="{{ TOMCAT_ROOT }}" mv "{{ ROOT }}/apache-tomcat-8.5.41" {{ TOMCAT_ROOT }}
    
    - name: remove non-essentials files from tomcat directory
      shell: find {{ TOMCAT_ROOT }} -maxdepth 1 -type f -delete
    
    - name: remove non-essentials folders from tomcat directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ TOMCAT_ROOT }}/webapps/ROOT"
        - "{{ TOMCAT_ROOT }}/webapps/docs"
        - "{{ TOMCAT_ROOT }}/webapps/examples"
        - "{{ TOMCAT_ROOT }}/webapps/manager"

    - name: download jenkins.war
      get_url:
        url: https://updates.jenkins-ci.org/latest/jenkins.war
        dest: "{{ TOMCAT_ROOT }}/webapps"
