---

- name: setup jenkins slave on ubuntu
  hosts: jenkins_slave
  gather_facts: false
  become: true
  tasks:
    - name: install git openjdk-8-jdk
      apt:
        name:
          - git
          - openjdk-8-jdk
