---

- name: setup jenkins slave on ubuntu
  hosts: jenkins_slave
  gather_facts: false
  become: true
  tasks:
    - name: install openjdk-8-jre
      apt-get:
        name:
          - openjdk-8-jre
