---

- name: setup jenkins master on ubuntu
  
  hosts: jenkinsmaster
  
  gather_facts: false
  
  become: true
  
  vars:
    ROOT: /root
    TOMCAT_ROOT: "{{ ROOT }}/tomcat"
    VER: 8.5.41
    TOMCAT_TAR: "apache-tomcat-{{ VER }}.tar.gz"
    APACHE_TOMCAT: apache-tomcat

  tasks:

  - name: uninstall old docker versions
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: add docker official gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

  - name: install docker-ce
    apt:
      name:
        - aptitude
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce
      update_cache: yes

  - name: pull jenkins image
    docker_image:
      name: balajipothula/jenkins:latest
      source: pull
    debugger: on_failed
          
  - name: download tomcat
    get_url:
      url: "http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v{{ VER }}/bin/{{ TOMCAT_TAR }}"
      dest: "{{ ROOT }}/{{ TOMCAT_TAR }}"
        
  - name: extract tomcat tarball
    unarchive:
      remote_src: yes
      src: "{{ ROOT }}/{{ TOMCAT_TAR }}"
      dest: "{{ ROOT }}"
        
  - name: remove tomcat tarball
    file:
      path: "{{ ROOT }}/{{ TOMCAT_TAR }}"
      state: absent
        
  - name: rename tomcat directory
    command: creates="{{ TOMCAT_ROOT }}" mv "{{ ROOT }}/{{ APACHE_TOMCAT }}-{{ VER }}" {{ TOMCAT_ROOT }}

  - name: remove tomcat extracted directory
    file:
      path: "{{ ROOT }}/{{ APACHE_TOMCAT }}-{{ VER }}"
      state: absent
    
  - name: remove non-essentials files from tomcat directory
    shell: find {{ TOMCAT_ROOT }} -maxdepth 1 -type f -delete

  - name: find .bat files in tomcat bin directory
    find:
      path: "{{ TOMCAT_ROOT }}/bin"
      patterns: "*.bat"
    register: bat

  - name: remove .bat files from tomcat bin directory
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ bat.files }}"
   
  - name: remove non-essentials folders from tomcat directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ TOMCAT_ROOT }}/webapps/ROOT"
      - "{{ TOMCAT_ROOT }}/webapps/docs"
      - "{{ TOMCAT_ROOT }}/webapps/examples"
      - "{{ TOMCAT_ROOT }}/webapps/host-manager"
      - "{{ TOMCAT_ROOT }}/webapps/manager"

  - name: download jenkins.war
    get_url:
      url: https://updates.jenkins-ci.org/latest/jenkins.war
      dest: "{{ TOMCAT_ROOT }}/webapps/ROOT.war"

  - name: run jenkins container
    docker_container:
      name: jenkins
      image: balajipothula/jenkins:latest
      volumes:
        - /root/tomcat:/tomcat
      ports:
        - 8080:8080
      command: sh
