---

- name: setup jre
  hosts: tomcat
  remote_user: ec2-user
  gather_facts: true
  vars:
    HOME: "{{ ansible_env.HOME }}"
    PATH: "{{ ansible_env.PATH }}"
    JRE_ROOT: "{{ HOME }}/jreroot"

  tasks:

  - name: download jre tarball
    get_url:
      url: "https://github.com/frekele/oracle-java/releases/download/8u212-b10/jre-8u212-linux-x64.tar.gz"
      dest: "{{ HOME }}"

  - name: extract jre tarball
    unarchive:
      remote_src: yes
      src: "{{ HOME }}/jre-8u212-linux-x64.tar.gz"
      dest: "{{ HOME }}"

  - name: remove jre tarball
    file:
      path: "{{ HOME }}/jre-8u212-linux-x64.tar.gz"
      state: absent

  - name: rename jre directory
    command: creates="{{ JRE_ROOT }}" mv "{{ HOME }}/jre1.8.0_212" "{{ JRE_ROOT }}"

  - name: remove jre extracted directory
    file: path="{{ HOME }}/jre1.8.0_212" state=absent

  - name: remove non essential directory jre directory
    file: path="{{ JRE_ROOT }}/man" state=absent

  - name: set jre bin path
    lineinfile:
      path: "{{ HOME }}/.bashrc"
      line: "export PATH={{ PATH }}:{{ HOME }}/jreroot/bin"

  - name: set jre home path
    lineinfile:
      path: "{{ HOME }}/.bashrc"
      line: "export JRE_HOME={{ HOME }}/jreroot/bin"
