---

- name: setup tomcat
  hosts: tomcat
  remote_user: ec2-user
  gather_facts: true
  vars:
    HOME: "{{ ansible_env.HOME }}"
    TOMCAT_HOME: "{{ HOME }}/tomcat"
    VER: 8.5.45
    TOMCAT_TAR: "apache-tomcat-{{ VER }}.tar.gz"
    APACHE_TOMCAT: apache-tomcat

  tasks:

  - name: download tomcat
    get_url:
      url: "http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v{{ VER }}/bin/{{ TOMCAT_TAR }}"
      dest: "{{ HOME }}/{{ TOMCAT_TAR }}"
  - name: extract tomcat tarball
    unarchive:
      remote_src: yes
      src: "{{ HOME }}/{{ TOMCAT_TAR }}"
      dest: "{{ HOME }}"
  - name: remove tomcat tarball
    file:
      path: "{{ HOME }}/{{ TOMCAT_TAR }}"
      state: absent
  - name: rename tomcat directory
    command: creates="{{ TOMCAT_HOME }}" mv "{{ HOME }}/{{ APACHE_TOMCAT }}-{{ VER }}" {{ TOMCAT_HOME }}

  - name: remove tomcat extracted directory
    file:
      path: "{{ HOME }}/{{ APACHE_TOMCAT }}-{{ VER }}"
      state: absent
  - name: find non essential files from tomcat directory
    find:
      path: "{{ TOMCAT_HOME }}"
      file_type: file
      depth: 1
    register: nonessential
  - name: remove non-essential files from tomcat directory
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ nonessential.files }}"

  - name: find .bat files in tomcat bin directory
    find:
      path: "{{ TOMCAT_HOME }}/bin"
      patterns: "*.bat"
    register: bat
  - name: remove .bat files from tomcat bin directory
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ bat.files }}"

  - name: remove non-essentials folders from tomcat directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
#     - "{{ TOMCAT_HOME }}/webapps/HOME"
      - "{{ TOMCAT_HOME }}/webapps/docs"
      - "{{ TOMCAT_HOME }}/webapps/examples"
      - "{{ TOMCAT_HOME }}/webapps/manager"

  - name: start tomcat
    command: "nohup {{ TOMCAT_HOME }}/bin/startup.sh"
